### ISSUE TITLE
"dependent on other PRs being merged"

### ISSUE THREAD

**Issue by robynbergeron** [ansible/ansibullbot#9] opened 2015-11-30 14:31 UTC
https://github.com/ansible/ansible-modules-core/pull/2586 <- as seen here, not the first time I've seen such requirements.

How do we handle that with ansibullbot? special snowflake label?

**Comment by gregdek** [comment] 2016-03-24 10:52
This will be a perfect use case for #53 -- closing this as a duplicate of that.

**Closed by gregdek** 2016-03-24 10:52 UTC
