### ISSUE TITLE
Component matching matched everyone who created a plugin

### ISSUE THREAD

**Issue by samdoran** [ansible/ansibullbot#860] opened 2018-02-13 23:06 UTC
On issue [#21595](https://github.com/ansible/ansible/issues/21595), component matching seems to have matched everyone in `lib/ansible/plugins` and was spamming folks with `@` mentions.

Not sure what the original comments looked like.

From @mattclay:
> The bot seems to be commenting the same thing about every 8 days.

From @gundalow:
> it's notified everyone that's created a plugin

**Comment by mattclay** [comment] 2018-02-13 23:17
Approximately every 8 days the bot listed all the files it though matched the PR. The matching was probably erroneous the first time, but then to make matters worse it repeated that same very long comment regularly.

**Comment by mkrizek** [comment] 2018-06-22 17:30
I can't reproduce this and can't see what the original issue looked like since the original issue has been altered before GitHub had introduced the feature to see issue's history. We'll see if that happens again.

**Comment by mkrizek** [comment] 2020-08-24 10:27
> I can't reproduce this and can't see what the original issue looked like since the original issue has been altered before GitHub had introduced the feature to see issue's history. We'll see if that happens again.

Closing per above. Please re-open if you see the issue again, thanks!

**Closed by mkrizek** 2020-08-24 10:27 UTC
Labels: bug
