### ISSUE TITLE
27517 missing network label for nxos component

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#692] opened 2017-08-02 16:40 UTC
https://github.com/ansible/ansible/issues/27517

was raised against an nxos component, though the `networking` label wasn't added

**Comment by jctanner** [comment] 2017-10-18 21:01
The user typed `nxos_port_channel` instead of `nxos_portchannel`. Duplicate of https://github.com/ansible/ansibullbot/issues/462

**Closed by jctanner** 2017-10-18 21:01 UTC
