### ISSUE TITLE
No command to re-open an issue

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansibullbot#721] opened 2017-08-20 16:03 UTC
There is no command to re-open an issue which is closed by ansibot

**Comment by Akasurde** [comment] 2017-08-20 16:05
I am unable to re-open https://github.com/ansible/ansibullbot/issues/721 as I am not a maintainer of module or reporter of the bug.

**Comment by jctanner** [comment] 2017-08-22 01:45
Duplicate of https://github.com/ansible/ansibullbot/issues/222

**Closed by jctanner** 2017-08-22 01:45 UTC
