### ISSUE TITLE
prbot does not handles state well

### ISSUE THREAD

**Issue by resmo** [ansible/ansibullbot#43] opened 2016-02-27 09:43 UTC
I did a deeper review how the prbot is working and I found that it does not handle state correctly. 

The PR defines actions based on current comments and labels, it also handles boilerplates e.g. warning for current comments an label. 

However it does not implicate the actions. 

As a result of it, the bot could suggest giving a warning for a PR in community_review even if the actions has a shipit. I also found that if the maintainer of a module changes, it is not going to be handled correctly.

(Ironically this is what all ansible modules have to handle and what ansible is all about... :) )

So how we can fix that:

1. we find the current state
2. find out in which state the PR should be aka desired state
3. we get the path from current state to desired state by defining actions.

I don't see a easy way to implement this properly in the current bot. I plan to give it a rewrite this weekend. 

However I also make a PR for a few problems I found while testing the current bot.

**Comment by gregdek** [comment] 2016-03-03 15:09
Yes, it's imperfect, no question -- largely because it's grown organically from ad-hoc additions.  Happy to see your rewrite; I'm sure it will be better code. :) 

Part of the problem is that some of our states are not fully determinate.

Will you submit the PR as basically new python files in this repo? That would be useful.

**Comment by resmo** [comment] 2016-03-03 16:11
yes, it is a new python file and will make a pr when ready, you can get an idea of it on https://github.com/resmo/ansibullbot/blob/feature/triage/triage.py

**Comment by gregdek** [comment] 2016-03-21 17:08
Since we've rebased on @resmo's bot that does handle state properly, closing this. Thanks @resmo!

**Closed by gregdek** 2016-03-21 17:08 UTC
