### ISSUE TITLE
needs_rebase is added even though it shows false in status

### ISSUE THREAD

**Issue by bcoca** [ansible/ansibullbot#1154] opened 2019-01-23 21:25 UTC
https://github.com/ansible/ansible/pull/50172

**Comment by wilmardo** [comment] 2019-02-01 16:47
ansible/ansible#50417 < my PR seems to hit this bug as well. Rebased it today, the label hasn't been removed but the status shows `needs_rebase: False`

**Comment by gundalow** [comment] 2019-03-06 15:56
In the case of https://github.com/ansible/ansible/pull/50172 I think the problem is that

```
This PR was evaluated as a potentially problematic PR for the following reasons:

More than 50 changed files.
Such PR can only be merged by human. Contact a Core team member to review this PR on IRC: #ansible-devel on irc.freenode.net
``` was triggered, that shouldn't cause any labels to be added

**Comment by mkrizek** [comment] 2021-02-16 13:08
Closing per above.

**Closed by mkrizek** 2021-02-16 13:08 UTC
Labels: bug
