### ISSUE TITLE
implicit needs_contributor

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#686] opened 2017-07-31 13:45 UTC
Need to make the needs_contributor command implicit if the waiting_on_contributor label is applied, similar to needs_info

https://github.com/ansible/ansible/issues/27423

**Comment by mkrizek** [comment] 2018-05-17 12:33
I think this is a duplicate of https://github.com/ansible/ansibullbot/issues/896 which we fixed.

**Closed by mkrizek** 2018-05-17 12:33 UTC
