### ISSUE TITLE
needs revision added for no reason

### ISSUE THREAD

**Issue by bcoca** [ansible/ansibullbot#98] opened 2016-05-26 14:48 UTC
I've fixed several of these today, here is an example:

https://github.com/ansible/ansible-modules-core/pull/3686

**Comment by alikins** [comment] 2016-05-26 15:38
https://github.com/ansible/ansible-modules-core/pull/3686#issuecomment-221712563 points to github detecting merge conflicts after the module rename, and then the bot moving it to needs_review. 

Needing rebase seems reasonable for needs_review, with the caveat that the bot doesn't record why it moved to needs_review, so doesn't know to unset that. 

And there was a new commit force pushed at https://github.com/ansible/ansible-modules-core/pull/3686/commits/909c05066e45f1bc4fbfad8eb6031493ca7e359d so that should also qualify as need review.

**Comment by gregdek** [comment] 2016-06-10 17:59
Yeah, it looks like we're not adding boilerplate when the case "needs_revision_not_mergeable" is detected.

**Comment by gregdek** [comment] 2016-06-10 18:20
Actually, no, that should be working. Not sure what the cause is.

**Comment by bcoca** [comment] 2016-07-25 12:34
https://github.com/ansible/ansible-modules-core/pull/4248 <= this one needed rebase also, but got needs_review

**Comment by gregdek** [comment] 2016-07-25 12:38
We don't put tickets automatically into needs_rebase anymore; that's now an additional state that we can choose to put it into. It went into needs_review because it failed shippable. Note the text in the comment:

"Thanks @xiaozhizhu for this PR. This PR requires revisions, either because it fails to build or by reviewer request."

**Comment by bcoca** [comment] 2016-07-25 12:48
OK, this one is hard to detect, I manually updated it, will the bot respect that?

**Comment by gregdek** [comment] 2016-07-25 13:03
Lemme check. I think needs_rebase is now "bot ignored", but I will double check and make sure that's the case.

**Comment by gregdek** [comment] 2016-07-25 13:05
OK, needs_rebase will now be ignored by the bot.

**Comment by jctanner** [comment] 2017-01-03 22:05
This shouldn't be a problem anymore except in rare cases.

**Closed by jctanner** 2017-01-03 22:05 UTC
