### ISSUE TITLE
ansibot does not pick up authors from module

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansibullbot#1049] opened 2018-09-24 12:17 UTC
There seems to be a problem with ansibot not picking up authors from modules.
- https://github.com/ansible/ansible/issues/45970
- https://github.com/ansible/ansible/pull/46060
- https://github.com/ansible/ansible/pull/46068

**Comment by dagwieers** [comment] 2018-09-24 12:17
cc @willthames @gundalow

**Comment by dagwieers** [comment] 2018-09-24 12:55
If ansibot returns an empty maintainers-list, we should probably fallback to the default for $team_ansible. And if this is the case, I would propose we remove $team_ansible (and empty container) from BOTMETA.yml ?

PS It is unclear to me what $team_ansible really is used for, and I would suggest using a better marker for this.

**Comment by jctanner** [comment] 2018-09-24 13:16
This is being caused by component matcher's get_meta_for_file not calling find_module_match and using the metadata provided.

```
(Epdb) pp self.component_matcher.find_module_match('route53')[0].get('authors')
['bpennypacker', u'jimbydamonk']
(Epdb) pp self.component_matcher.get_meta_for_file('lib/ansible/modules/cloud/amazon/route53.py').get('authors')
[]
```

**Comment by felixfontein** [comment] 2018-10-07 07:42
This still seems to be a problem: ansible/ansible#46583

**Comment by webknjaz** [comment] 2018-10-07 11:46
@felixfontein that one is double weird:
```json
2018-10-07 13:26:13,475 INFO url: https://github.com/ansible/ansible/issues/46583
2018-10-07 13:26:13,476 INFO title: Ansible v2.70  - Docker Swarm is unable to create the swarm manager 
2018-10-07 13:26:13,476 INFO component[t]: docker_swarm module
2018-10-07 13:26:13,476 INFO component[m]: lib/ansible/modules/cloud/docker/docker_swarm.py
{'assign': [],
 'cancel_ci': False,
 'cancel_ci_branch': False,
 'close': False,
 'close_migrated': False,
 'comments': [],
 'merge': False,
 'newlabel': ['support:core'],
 'open': False,
 'rebuild': False,
 'unassign': [],
 'unlabel': ['needs_maintainer', 'support:community']}
Take recommended actions (y/N/a/R/T/DEBUG)? DEBUG
```

cc @jctanner

**Comment by webknjaz** [comment] 2018-10-07 19:04
@pilou- I want to merge py3 compat PR first, because it's got a lot in it and I'd like to avoid having to deal with conflicts.

**Comment by felixfontein** [comment] 2018-10-20 22:14
This still isn't fixed, right? (Happened again in ansible/ansible#47383, agronholm as docker_volume author wasn't identified.)

**Comment by dagwieers** [comment] 2018-10-21 19:48
@felixfontein No, it is not fixed. My PR to trigger this has not been updated.

**Comment by felixfontein** [comment] 2018-10-21 19:54
@dagwiiers what's interesting is that it seems to work in *some* cases. For example, in ansible/ansible#47393 it did work. (A difference is that docker_image has a BOTMETA entry, though only with $team_ansible, which is an empty list.)

**Comment by gundalow** [comment] 2018-10-23 17:40
Still failing https://github.com/ansible/ansible/pull/47490

**Comment by gundalow** [comment] 2018-11-08 13:51
http://dash.tannerjc.net/graph `repo:ansible label:needs_maintainer
Shows us that the number of issues/PRs with `label/needs_maintainer` opened has increased dramatically from September

**Comment by felixfontein** [comment] 2018-11-11 14:07
Is this already deployed? If yes, it still doesn't always work: ansible/ansible#48536

**Comment by webknjaz** [comment] 2018-11-11 16:35
@felixfontein yes, it should be deployed. What is the expected result?

**Comment by webknjaz** [comment] 2018-11-11 16:39
oh. I see the comment.

**Comment by webknjaz** [comment] 2018-11-11 16:39
@jctanner @gundalow we probably need to implement a pre-issue/PR "debug" command, so that we could trace the decision process better.

**Comment by webknjaz** [comment] 2018-11-11 17:00
bot status shows the correct maintainers list:

```

changelogs/fragments/48536-docker_volume-labels.yml
support: community
maintainers:

lib/ansible/modules/cloud/docker/docker_volume.py
support: community
maintainers: agronholm akshay196 danihodovic dariko felixfontein jwitko kassiansun tbouvet

test/integration/targets/docker_volume/tasks/tests/basic.yml
support: community
maintainers: agronholm akshay196 danihodovic dariko felixfontein jwitko kassiansun tbouvet

```

**Comment by webknjaz** [comment] 2018-11-11 17:06
@mkrizek is it possible that bot made a decision based on the outdated cache?

**Comment by jctanner** [comment] 2018-11-11 18:35
@felixfontein what didn't "work"?

**Comment by felixfontein** [comment] 2018-11-11 19:10
@jctanner The module author was not pinged by ansibot. Only the maintainers from BOTMETA were pinged.

**Comment by jctanner** [comment] 2018-11-11 21:15
```
ansibullbot/triagers/plugins/component_matching.py
 95     # Reduce the set of notifiers
 96     for x in CM_MATCHES:
 97         for y in x[u'notify']:
 98             if y not in cmeta[u'component_notifiers']:
 99                 cmeta[u'component_notifiers'].append(y)

ansibullbot/triagers/plugins/notifications.py
 75         fassign = sorted(set(meta[u'component_maintainers'][:])) --> get assigned
 76         fnotify = sorted(set(meta[u'component_notifiers'][:]))   --> get pinged

(Epdb) pp sorted(set([y for y in x['maintainers'] for x in CM_MATCHES]))
[u'agronholm',
 u'akshay196',
 u'danihodovic',
 u'dariko',
 u'felixfontein',
 u'jwitko',
 u'kassiansun',
 u'tbouvet']

(Epdb) pp sorted(set([y for y in x['notify'] for x in CM_MATCHES]))
[u'akshay196',
 u'danihodovic',
 u'dariko',
 u'felixfontein',
 u'jwitko',
 u'kassiansun',
 u'tbouvet']
```

**Comment by jctanner** [comment] 2018-11-12 13:32
After thinking about this more since yesterday, I remembered more about the history of this code path. Originally, the intent was to assign maintainers to tickets. We have so few maintainers that can be assigned to tickets though and the ansible-network team specifically asked to not be assigned, so the feature was turned off. It was presumed though that being assigned was going to trigger subscription/notification. Without assignment, that logic breaks down and I'm not sure that I or others realized that at the time. 

So we have two options:

A) in component matcher's get_file_meta function, auto-include maintainers into notifiers.
B) use the patch in my last comment to merge the two within the notification plugin

**Comment by gundalow** [comment] 2018-11-12 15:19
C) Remove the Network "hack" and they should remove themselves from BOTMETA

**Comment by dagwieers** [comment] 2018-11-12 17:24
@gundalow Indeed, I saw the network team being mentioned for all the ACI and Meraki related bugs/PRs, and I assumed they *wanted* to be notified as they added themselves in BOTMETA. But it seems they may have *overreached* by accident.

**Comment by felixfontein** [comment] 2018-12-03 05:40
Any news on this?

**Closed** 2018-12-05 15:47 UTC
Labels: P1, bug

**Comment by gundalow** [comment] 2018-12-05 15:53
Everybody, we believe this is fixed now. Will take the bot upto 7 days to walkover all existing issues and PR. 

If you see any new issues/PRs that are wrong please let us know
@webknjaz Thanks for fixing this!

**Comment by gundalow** [comment] 2018-12-05 16:02
Bot seemed to be correctly notifying now https://github.com/ansible/ansible/issues/48785#issuecomment-444538263

**Comment by gundalow** [comment] 2018-12-05 16:31
Bot is notifying people a lot, @webknjaz is investigating
