### ISSUE TITLE
Add automated final comment to merged/closed docs PRs

### ISSUE THREAD

**Issue by samccann** [ansible/ansibullbot#1645] opened 2022-03-18 19:40 UTC
To encourage contributors, we'd like to add the following comment after each docs PR is closed or merged:

Thanks for your Ansible docs contribution! We talk about Ansible documentation on maxtrix at [#docs:ansible.im](https://matrix.to/#/#docs:ansible.im) and on libera IRC at #ansible-docs if you ever want to join us and chat about the docs! We meet there on Tuesdays (see [the Ansible calendar](https://github.com/ansible/community/blob/main/meetings/README.md)) and welcome additions to our [weekly agenda items](https://github.com/ansible/community/issues/643) -  scroll down to find the upcoming agenda and add a comment to put something new on that agenda.

**Comment by mkrizek** [comment] 2022-03-21 09:22
With the current implementation of the bot this is not possible because bot does not scan closed issues/PRs. However I suspect that with GraphQL we could query closed/merged PRs with `docs_only` label that were closed X hours ago and process them in order to add such a comment. I'd need to investigate it more and be fine with adding such functionality.

Also, there is a related issue in https://github.com/ansible/ansibullbot/issues/1067 to mention Docs WG on docs issues/PRs. Is that something that would be effectively a duplicate of this?

Alternatively we could implement the above issue which would make the bot add such a comment on every new `docs_only` issue as opposed to after a PR is closed/merged which is how the current "working groups notifications" functionality works - although with collections it is not needed.

I am fine with either, let me know what you think.

**Comment by mkrizek** [comment] 2022-03-21 09:23
https://github.com/ansible/ansibullbot/blob/devel/templates/community_workgroups.j2

**Comment by samccann** [comment] 2022-03-21 14:05
I'm fine with it happening when the PR is opened for sure.  Can we modify ^^ to mention the matrix channel as well?

**Comment by mkrizek** [comment] 2022-03-21 15:28
@samccann I created #1646 that adds the proposed comment on every PR that has `docs_only` label. It means that every new PR that gets labeled `docs_only` will receive that comment but also all existing PRs already labeled `docs_only` will receive that comment. Also, any currently existing PR without that label will receive the comment once `docs_only` label is applied anytime in future.

Let me know if you want to change to newly created issues only; I wonder if that would be better, less noisy.

The PR closes https://github.com/ansible/ansibullbot/issues/1067 and this issue.

**Comment by samccann** [comment] 2022-03-21 16:02
There are only about 24 docs-only PRs and I'm fine with the extra comment on each. Might shake loose some attention because a few have been lingering for a time.

Thanks for  this!

**Closed as completed** 2022-03-22 08:43 UTC
