### ISSUE TITLE
Don't set labels or mention people on broken merges

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#837] opened 2017-12-20 10:03 UTC
https://github.com/ansible/ansible/pull/34028 shows
* a failed rebase
* Lots of labels added
* lots of people notified

We should detect these type of cases and the bot shouldn't updates labels or `@mentions`

**Comment by pilou-** [comment] 2017-12-20 10:44
Bot could:
- disable notifications when there are more than 10 commits (PR with more than 10 commits aren't mergeable by the bot, see #835)
- add `needs_rebase` label to these pull-request (because submitter must rebase the PR)

**Comment by dagwieers** [comment] 2017-12-20 10:55
This is a duplicate of https://github.com/ansible/ansibullbot/issues/787

**Comment by MarkusTeufelberger** [comment] 2017-12-28 10:29
Another one: https://github.com/ansible/ansible/pull/34264

**Closed** 2018-01-04 21:47 UTC
Labels: bug, P2
