### ISSUE TITLE
Labels to apply to PRs related to tests

### ISSUE THREAD

**Issue by samdoran** [ansible/ansibullbot#764] opened 2017-09-11 19:16 UTC
We need to decide what labels we would like applied to test related PRs. The current default label is `test`. We were also applying `test_pull_requests` label via `BOTMETA.yml`, but that was removed in a recent PR.

**Comment by pilou-** [comment] 2017-09-14 18:04
1. #28926 added `test_pull_requests` but then `test` was applied to
2. #28956 removed `test_pull_requests` but entry without values doesn't seem handled
3. #29660 "Labels were removed in a previous PR, and now the bot is upset."

**Comment by gundalow** [comment] 2017-10-05 17:30
From Testing Working Group

[18:29] <@gundalow> #agreed Drop label:test_pull_requests just use label:test (ansibullbot#764)

**Comment by pilou-** [comment] 2017-10-08 23:21
Using an `test/:` key without any value in `.github/BOTMETA.yml`, I am not able to reproduce the error mentionned by @samdoran, see: https://github.com/ansible/ansible/pull/29660#issuecomment-335045467. As far as I known, reverting 2b02d482a1d0e1cf581a56fc4062c9b5e9eabab6 would allow `test` label to be applied.

**Comment by samdoran** [comment] 2017-10-10 15:13
But we don't want both `test` and `test_pull_requests` applied. `test_pull_requests` in applied in the Bot code, not via `BOTMETA.yml`. So we need to change it there rather than in `BOTMETA.yml`.

**Comment by pilou-** [comment] 2017-10-10 15:17
> But we don't want both test and test_pull_requests applied. test_pull_requests in applied in the Bot code, not via BOTMETA.yml.

AFAIK Ansibullbot doesn't add `test_pull_requests` label (not since https://github.com/ansible/ansibullbot/commit/f9e1325521d2ec2a47ed7cf844ff2c2177d40bb4).

**Comment by pilou-** [comment] 2017-10-18 14:32
This issue can be closed:
- ansible/ansible#31472 has been merged
- since Ansibullbot behavior is OK: `test`label has been added to test related PR (for example: ansible/ansible/#31870)

**Closed** 2017-10-18 20:50 UTC

**Comment by dagwieers** [comment] 2018-06-22 08:36
Can we also take the following actions:
- Migrate existing `test_pull_requests` labeled issues to `test` label
- Decommision the `test_pull_requests` label
- Update the ansibot documentation and remove the references to test_pull_requests

I don't mind doing this, but I need to make sure this is actually wanted.
