### ISSUE TITLE
Incorrect files identified in the description

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#1115] opened 2018-12-04 19:48 UTC
https://github.com/ansible/ansible/issues/49232

```
COMPONENT NAME
firewalld
```
Caused:

```
Files identified in the description:

lib/ansible/galaxy/data/apb/vars/main.yml.j2
lib/ansible/modules/commands/command.py
lib/ansible/modules/system/firewalld.py
lib/ansible/modules/system/interfaces_file.py
lib/ansible/modules/utilities/logic/include_vars.py
lib/ansible/parsing/utils/yaml.py
lib/ansible/playbook/loop_control.py
lib/ansible/plugins/lookup
test/integration/targets/include_vars/vars/environments/development/services/webapp.yml
test/integration/targets/shadowed_module/library/tags

```
Which I don't understand

## https://github.com/ansible/ansible/issues/49291

```
COMPONENT NAME
elb_application_lb
```

```
lib/ansible/modules/cloud/amazon/elb_application_lb.py
lib/ansible/modules/cloud/amazon/elb_target_group.py
lib/ansible/parsing/utils/yaml.py
lib/ansible/playbook/loop_control.py
```

## https://github.com/ansible/ansible/issues/49452

```
COMPONENT NAME
route53_facts
https://docs.ansible.com/ansible/latest/modules/route53_facts_module.html
```

```
lib/ansible/modules/cloud/amazon/route53_facts.py
lib/ansible/modules/cloud/amazon/route53_zone.py
lib/ansible/modules/utilities/logic/debug.py
lib/ansible/parsing/utils/yaml.py
```

**Comment by mkrizek** [comment] 2020-08-24 11:08
Duplicate of https://github.com/ansible/ansibullbot/issues/1100

Tested locally and the bot identified the correct component (even before the component command was used).

**Closed by mkrizek** 2020-08-24 11:08 UTC
Labels: bug
