### ISSUE TITLE
lib/ansible/parsing/utils/yaml.py is slipping into the component matches

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1100] opened 2018-11-19 22:41 UTC
https://github.com/ansible/ansible/issues/46682

**Comment by jctanner** [comment] 2018-11-19 22:41
```https://github.com/ansible/ansible/pull/36331	WIP: Allow certain, simple Jinja values to be unquoted.
https://github.com/ansible/ansible/issues/44933	Squash facts from loops to lists
https://github.com/ansible/ansible/issues/45280	vmware_host_config_facts and vmware_guest_facts
https://github.com/ansible/ansible/issues/45391	github_release: Allow anonymous access
https://github.com/ansible/ansible/issues/45395	Customize the variable precedence
https://github.com/ansible/ansible/issues/45578	Need for additional subclass argument in construct_url() method of ACIModule class
https://github.com/ansible/ansible/issues/45644	vault identifier is not exposed in tower_credential
https://github.com/ansible/ansible/issues/45707	SSH Host Key Pinning and Validation
https://github.com/ansible/ansible/issues/45911	pipenv, pipenv_facts: new module request
https://github.com/ansible/ansible/issues/45948	Netbox: Creating Ansible modules
https://github.com/ansible/ansible/issues/45983	storage: Add gluster_heal_facts module to extract cluster heal status.
https://github.com/ansible/ansible/issues/46078	VMware: Add conversion disk to thin when vm cloned
https://github.com/ansible/ansible/issues/46215	Add a version of the combine-filter that merges in reversed order
https://github.com/ansible/ansible/issues/46252	Choosable Color for Hostname in PLAY
https://github.com/ansible/ansible/issues/46300	Ability to target different version of PowerShell, mainly PowerShell 6.x
https://github.com/ansible/ansible/issues/46308	Add arrays support for xfconf module
https://github.com/ansible/ansible/issues/46508	add 'one_vm_facts' to cloud/opennebula
https://github.com/ansible/ansible/issues/46532	Missing labels field in gcp_compute_instance
https://github.com/ansible/ansible/issues/46537	[azure_rm_virtualmachine] add support for StandardSSD_LRS
https://github.com/ansible/ansible/issues/46540	win_acl to have /reset capability of icacls
https://github.com/ansible/ansible/issues/46661	Optionally make not matching any hosts a fatal error
https://github.com/ansible/ansible/issues/46682	Solaris - pkg5 module - Provide a boolean switch to enable/disable publisher refresh
https://github.com/ansible/ansible/issues/46769	Add 'handlers_from' option to import_role and include_role
https://github.com/ansible/ansible/issues/46777	Add aggregate method in nxos_acl module
https://github.com/ansible/ansible/issues/46829	FAILURE-messages not informative enough
https://github.com/ansible/ansible/issues/47092	Enhancement: JBoss EAP Server Management Core Module
https://github.com/ansible/ansible/issues/47156	capabilities module has inscrutable behavior, it should be replaced with a simpler implementation
https://github.com/ansible/ansible/issues/47329	VMware: Request for support SATA disk controller
https://github.com/ansible/ansible/issues/47343	[getent module] getent wrapper should return associative arrays instead of lists
https://github.com/ansible/ansible/issues/47577	Hash support for ios_user
https://github.com/ansible/ansible/issues/47609	Fastly Ansible Module
https://github.com/ansible/ansible/issues/47649	VMware: Add private vlan to distributed switch
https://github.com/ansible/ansible/issues/47654	pip: Add "constraints" value
https://github.com/ansible/ansible/issues/47713	VMware: should have choice to specify vsan datastore name when configuring vsan cluster
https://github.com/ansible/ansible/issues/47770	Integration with Mozilla SOPS for encrypted files
https://github.com/ansible/ansible/issues/47898	Add Endpoint Type Support for ec2_vpc_endpoint Module
https://github.com/ansible/ansible/issues/48134	Ability to temporarily mount a filesystem without altering /etc/fstab
https://github.com/ansible/ansible/issues/48334	VMware: Feature request for enable VBS when creating Win10 VM on ESXi 6.7
https://github.com/ansible/ansible/issues/48353	Specify home directory in ipa_user module
https://github.com/ansible/ansible/issues/48354	A lookup plugin to fetch secrets from Netbox
https://github.com/ansible/ansible/issues/48399	Suspend other tasks during "rescue"
https://github.com/ansible/ansible/issues/48410	Featured ansible_failed_task.host info on ansible_failed_task
https://github.com/ansible/ansible/issues/48422	add configurable password_retries to prevent account lockout
https://github.com/ansible/ansible/issues/48489	Intra-Tenant Contract Deployment
https://github.com/ansible/ansible/issues/48706	Add netStackInstanceKey to vmware_vmkernel
https://github.com/ansible/ansible/issues/48709	New parameter for `include_role` to pass role variables
https://github.com/ansible/ansible/issues/48780	Add "creates" parameter to archive module
https://github.com/ansible/ansible/issues/48825	Adding Datastore lock retry for netconf_config module
https://github.com/ansible/ansible/issues/48866	Allow import_tasks to take wildcard
https://github.com/ansible/ansible/issues/48874	Consistent use of docker config path for docker modules```

**Comment by gundalow** [comment] 2019-03-06 16:26
Looks like this was still an issue 20 days ago https://github.com/ansible/ansible/issues?utf8=%E2%9C%93&q=is%3Aissue+%22lib%2Fansible%2Fparsing%2Futils%2Fyaml.py%22

**Comment by gundalow** [comment] 2019-04-05 10:02
Not seen in the past 29 days https://github.com/ansible/ansible/issues?utf8=%E2%9C%93&q=is%3Aissue+%22lib%2Fansible%2Fparsing%2Futils%2Fyaml.py%22+

Believe this was caused by having the following in the issue template:
```

```yaml
```

Bot has been updated to ignore this.

**Comment by mkrizek** [comment] 2020-08-24 10:48
Fixed in https://github.com/ansible/ansibullbot/pull/1423

**Closed by mkrizek** 2020-08-24 10:48 UTC
Labels: P1, bug
