### ISSUE TITLE
Can we avoid ansibot label/identification flapping

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansibullbot#1070] opened 2018-10-10 14:15 UTC
Here [#32181](https://github.com/ansible/ansible/issues/32181) is an example where ansibot, over a few months time, added comments going from state 1 to state B and back. Both for file identification as well as labels. (I marked the ansibot interventions as spam as it was harder to find any discussions due to its comments)

Most likely this is due to changes in heuristics (or maybe bugfix/regression/bugfix/regression).

But I wonder whether we can detect this, or maybe have a dry-run mode where running the (upcoming) new version against a set of issues to see what it intends to change. Then we can verify if these intended changes make sense or not before running it for real.

**Comment by webknjaz** [comment] 2018-10-10 15:41
It's probably happening because bot hits different branches/modes in its code. I've actually seen differences between bot in prod and locally run triaging for the same issue/PR.
So I think it's most likely a bug rather than conditions change over time.

**Comment by mkrizek** [comment] 2020-08-07 08:02
> Here [#32181](https://github.com/ansible/ansible/issues/32181) is an example where ansibot, over a few months time, added comments going from state 1 to state B and back. Both for file identification as well as labels. (I marked the ansibot interventions as spam as it was harder to find any discussions due to its comments)
> 
> Most likely this is due to changes in heuristics (or maybe bugfix/regression/bugfix/regression).

Correct, if it is a change in heuristics (a new feature) that would be expected. If it's a bug/regression then it needs to be fixed but we should track it in separate issues individually. As such I am going to close this issue.

> 
> But I wonder whether we can detect this, or maybe have a dry-run mode where running the (upcoming) new version against a set of issues to see what it intends to change. Then we can verify if these intended changes make sense or not before running it for real.

Historically this is exactly how the bot has been tested.

**Comment by mkrizek** [comment] 2020-08-07 08:03
> It's probably happening because bot hits different branches/modes in its code. I've actually seen differences between bot in prod and locally run triaging for the same issue/PR.
> So I think it's most likely a bug rather than conditions change over time.

That would likely be due to different state of cache on those machines.

**Closed by mkrizek** 2020-08-07 08:03 UTC
Labels: bug
